name: 🔀 Pipeline (PullRequest)

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  docs:
    name:
    uses: ./.github/workflows/docs.yml
