name: 🔀 Pipeline (Release)

on:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  trigger_docs:
    runs-on: [self.hosted]
    steps:
      - name: Trigger docs workflow
        uses: ./.github/workflows/docs.yml

