name: 🆕 Create Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: [self-hosted]
    steps:
      - name: release-please
        id: release
        uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.TEST_TOKEN }}
