name: 🆕 Create Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: [self-hosted]
    steps:
      - name: release-please
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: python
          package-name: release
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
